### ISSUE TITLE
GuidedTransform design problems blocking automated accounting/analysis

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#193]
GuidedTransform doesn't generate any intermediate relationships structure that isn't explicitly bound to the exact shape of the target dataservice. An example of this can be seen in the designation of 'biospecimen_genomic_file' but not 'participant_biospecimen' in the test_boyd_study transform_module.py. We should be able to identify relationships between things without knowing the layout of the target service api. This should be encoded at the standard CONCEPT level without reference to the target.

Code for checking relationships shouldn't need to change every time the dataservice decides to change a foreign key to a relationship table.

It also definitely does not account for value mispropagation from unencoded attribute relationships per https://github.com/kids-first/kf-lib-data-ingest/blob/master/docs/archive/design/merge_algorithm/DataFrame_Design_Complications_Motivating_The_Relationship_Graph.ipynb (the last problem) and will probably run afoul of the other barriers to merging as well.

We should talk about how to approach this. I think the transform_module in test_boyd_study returning dataservice entity keys like it currently does is a big mistake. I think returning standard concept keys might be ok.

**Comment by znatty22** [comment]
Yea let’s talk …

I think returning a dict from transform module with standard concept keys might be better but I think it might cause other problems later in transform that we’ll have to solve.

Most of these other issues are exactly what the graph-based transformation approach was meant to solve. I think we knew we would not be solving the value mispropagation due to merges, with guided transformation. We initially said we wouldn’t encode relationships into the standard concept graph either. 

So does this mean we should revisit graph based transformation now? Or could we use the compact merge algo which depends on knowing relationships in the interim?

**Comment by znatty22** [comment]
Also, I forgot that we define relationships among standard concepts in the target API https://github.com/kids-first/kf-lib-data-ingest/blob/master/kf_lib_data_ingest/target_apis/kids_first.py#L251. Graph based transformation uses that when reading the graph to build target service entities. The relationships are the traversal rules which govern which parts of the graph shouldn't be read when building various entities

**Comment by fiendish** [comment]
I see `CONCEPT.BIOSPECIMEN_GENOMIC_FILE` in that file but there shouldn't be such a thing because that's just a representational choice made by the dataservice and not something that exists.

**Comment by znatty22** [comment]
Regardless of whether we have accounting or not we need to implement these changes 

Summarizing the changes we discussed:

1. User writing the transform module will be responsible for merging all of their individual mapped dataframes into a single dataframe
2. Write this intermediate form of the data to a file so that post transform accounting can use it
3. Move the call to unique key creation from https://github.com/kids-first/kf-lib-data-ingest/blob/34745d4a55530dea8538c982f067a7fd489fca7b/kf_lib_data_ingest/etl/transform/transform.py#L378 to https://github.com/kids-first/kf-lib-data-ingest/blob/34745d4a55530dea8538c982f067a7fd489fca7b/kf_lib_data_ingest/etl/transform/guided.py#L176
