### ISSUE TITLE
Use ALIQUOT_ID as a Primary Key to CONCEPT.BIOSPECIMEN

### ISSUE THREAD

**Issue by liberaliscomputing** [kids-first/kf-lib-data-ingest#310]
For most of the X01 studies, a sample may be an aliquot. In CBTTC, however, an aliquot is an atomic level unit of biospecimen and a sample is a collection of aliquots. So, CBTTC uses the `external_aliquot_id` as a unique ID for a biospecimen entity. The current ingest extractor considers `BIOSPECIMEN.ID`, which is an `external_sample_id`, as a unique column and, in turn, accounting biospecimens against the ingest library will not be correct. For example, the Open DIPG (it is part of CBTTC) Chris Jones cohort that I am wrangling with the ingest library has 240 sample IDs and 410 aliquot IDs. If I use 410 as an expected count for `CONCEPT.BIOSPECIMEN`, it cannot pass the accounting.

**Comment by fiendish** [comment]
> The current ingest extractor considers BIOSPECIMEN.ID, which is an external_sample_id, as a unique column

Yes. This is a mistake. Combination of Sample ID and Aliquot ID (or just aliquot ID if we rule that it should include the sample ID as part of it's value) should always be the unique identifier for an BS entity, never sample ID alone.

**Comment by fiendish** [comment]
We should begin renaming concepts so that they are less confusing.

**Comment by znatty22** [comment]
I vote we use both `BIOSPECIMEN.ID` and `BIOSPECIMEN.ALIQUOT_ID` to form the `BIOSPECIMEN.UNIQUE_KEY`, but we might want to rename things to make it less confusing. Perhaps add another concept attribute called `BIOSPECIMEN.SAMPLE_NAME` or something similar and get rid of `BIOSPECIMEN.ALIQUOT_ID`. 

Then `BIOSPECIMEN.ID` would be used to store the aliquot ID and could be the required unique key component,  while `BIOSPECIMEN.SAMPLE_NAME` would be optional since not all studies have both sample and aliquot IDs.  

Biospecimen unique keys would be similar to the other compound unique keys like diagnosis unique keys. For diagnosis, both participant ID and diagnosis name are required to form the diagnosis unique key but the diagnosis event age in days is optional. The pipeline will use the required components and any optional components that exist to form the unique key.

**Comment by fiendish** [comment]
> Perhaps add another concept attribute called BIOSPECIMEN.SAMPLE_NAME or something similar and get rid of BIOSPECIMEN.ALIQUOT_ID.

I propose "Aliquot Group ID" to make the relationship clear

**Comment by liberaliscomputing** [comment]
FYI, in Nautilus, where CHOP curates all the samples, there are two columns, namely `parent_aliquot_id` and `aliquot_id`.

**Comment by fiendish** [comment]
After changing the fields, we have two options for value propagation:

1) We add a check such that you aren't allowed to have a parent/group/sample ID without an aliquot ID or vice versa.

2) We automatically populate aliquot ID if only parent/group/sample ID is set and vice versa.

**Comment by fiendish** [comment]
Still a bug.
