### ISSUE TITLE
Filter Entities for biospecimen_diagnosis

### ISSUE THREAD

**Issue by liberaliscomputing** [kids-first/kf-lib-data-ingest#312]
In CBTTC (and any sub-studies of CBTTC such as Open DIPG), we create `biospecimen_diagnosis` links only for tumor samples. For the Open DIPG Chris Jones cohort that I am wrangling with the ingest library, there are 410 samples and 343 are tumor samples. The transformation phase creates 410 BDs. Will there be any way to handle this without making separate packages or extract configs?

**Comment by fiendish** [comment]
> we create biospecimen_diagnosis links only for tumor samples

why?

**Comment by znatty22** [comment]
This could be handled if we let transform function return a single merged df (as we currently do) or a dict of dataframes. 

The keys in the dict of dataframes would be target concepts. If the dict of dataframes is returned instead of the single merged df, then only the target concepts represented by the dict keys would be built and passed into load stage. This way you could say I want to use a specific dataframe for a particular entity.

**Comment by fiendish** [comment]
I don't want any code changes for this until it's determined that this is actually a real problem and not someone wanting to do something that doesn't make any sense.

**Comment by znatty22** [comment]
@fiendish I agree, but I also wonder whether in the future a valid case may warrant this change 🤔... No need to change it if its not a problem now tho

**Comment by baileyckelly** [comment]
Specifically with cancers in our data model - the diagnosis is linked to the actual tumor - not directly to the participant. The participant can have multiple tumors over time and therefore multiple diagnoses (secondary malignancies etc). (Or the same diagnosis but it can be a relapse, progression, etc). The diagnosis is not linked to the blood or the saliva sample because that sample isn't what is "diagnosed." Similarly with structural birth defect studies - the blood/saliva sample doesn't carry the scoliosis or the orofacial cleft diagnosis/phenotype - the participant does. This is why we have the tumors linked to the diagnosis and not the "normal" samples.

**Comment by fiendish** [comment]
I consider this to be irrelevant. Your tumor sample only ever has any value in relation to a normal sample.

**Comment by liberaliscomputing** [comment]
Now, I understand why we have linked only tumor samples to `diagnosis`. At the same time, Avi seems making a reasonable point since a diagnosis carries a sampling **event**  and samples collected for this event are bound to that diagnosis together. And non-tumor samples will have a genomic meaning only when contextualized with their' pairing tumor samples.

**Comment by znatty22** [comment]
https://github.com/kids-first/kf-lib-data-ingest/pull/322 allows you to return different DataFrames for different target concepts. Regardless of whether it is correct or not to filter biospecimen-diagnosis down to only tumor samples, #322 makes it possible.

Closing this issue.
