### ISSUE TITLE
Possible issue with sqlite3worker on WSL2

### ISSUE THREAD

**Issue by torstees** [kids-first/kf-lib-data-ingest#540]
I think there may be some timing issue with the sqlite3worker on WSL. I have had weird issues with ids that simply refuse to make it to the database even though the insert statement was called (and thus the next time the ingestion was run, those without IDs were treated as new and end up with duplicate entries in FHIR). 

Would it be possible to make that database be based on plain sqlite3 based on an option in the __init__?

**Comment by fiendish** [comment]
I think this _should_ be possible. Minimally it will require changing when and where entries get written to the cache db.

**Comment by blackdenc** [comment]
@torstees Can you share your `/etc/wsl.conf` file? I don't think we officially support WSL/WSL2, but there are some settings you may need to change there that might help with the issue.

**Comment by torstees** [comment]
Sure, I'll paste it below, since it's not particularly long:

**Comment by blackdenc** [comment]
So this is just a guess, but I think the issue you're having might be related to `root = /mnt`. The WSL2 I/O performance is only on the Linux filesystem, it doesn't extend to the NTFS drives under `/mnt` so it's possible that the cache lookup is missing due to that. 

https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems

**Comment by torstees** [comment]
Well, I need files available to both windows and WSL with my current workflow when it comes to data ingestion and the entire system used for it lives in NTFS and will continue to be that way as long as I use Windows as my primary OS. However, I do have a work around if it doesn't seem appropriate to officially provide a solution.

**Comment by blackdenc** [comment]
You can still access the NTFS filesystem under `/mnt` without defining it as the root, but the application and dependencies should be installed under `/` in the Linux FS to avoid performance issues. I'm not sure if that'll work for your use-case, and most of the time cross-OS executables works fine, but in cases like this I'd still recommend running databases and application code inside the Linux VM.

**Comment by fiendish** [comment]
I do plan to make changes to remove the sqlite queueing thread, because fewer dependencies is usually better, but it's not clear yet how funneling requests into a queue because sqlite can't handle parallel writes (because it has no queueing process of its own) causes entries to be missed only on WSL.

**Comment by torstees** [comment]
@blackdenc Oh, I misunderstood where you were suspecting the problem lay. I'm pretty sure that wsl.conf was set up completely independent of the actual installation of the linux VM and that the mount point assigned to root doesn't indicate any of the VM's OS resides within NTFS. The scripts, though, those do live inside a regular ol' windows directory along with the SQLite database and the rest of the ETL input/output stuff.

**Comment by fiendish** [comment]
@torstees can you try the branch in https://github.com/kids-first/kf-lib-data-ingest/pull/555 and see if it helps?

**Comment by fiendish** [comment]
If the new code doesn't work, we can re-open the issue.
