### ISSUE TITLE
Should warehousing default to off?

### ISSUE THREAD

**Issue by chris-s-friedman** [kids-first/kf-lib-data-ingest#612]
I want to start a discussion about this: I think warehousing should default to off. 

Unless I have a special case where I *need* to warehouse the output of my ingest run, i always run `kidsfirst test` and `kidsfirst ingest` with the `--no_warehouse` flag. 

I'm curious if any of the other ingest package developers are warehousing the outputs of their ingests and how they feel about defaulting warehousing to be off.

**Comment by youngnm** [comment]
I always use the `--no_warehouse` flag so setting the default to off works for me.

**Comment by Christina-J-Diaz** [comment]
I haven't been using the flag, but when I first read about developing ingest packages I wondered if that was something I should always do...so I would be fine with setting the default to off.

**Comment by gsantia** [comment]
Probably less potential for mistakes that way

**Comment by fiendish** [comment]
I hate to admit that I also do this.

**Comment by liberaliscomputing** [comment]
In a long run, we would always persist extraction and transformation results into a data lake where we do data QC and knowledge discovery, etc. Admittedly, always flagging with it has also been a hassle for me :(

**Comment by znatty22** [comment]
I vote for the default to be warehousing off. Seems like we don't really use it right now so why keep it on. Can always change it back later 🤷 . 

Although it hasn't been much of a problem for me, since I know that if the env var for the warehouse url is not set in my env and I forgot to include the no warehouse flag, it defaults to turn warehousing off.
